---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm-2: #Имя машины
          ansible_host: 51.250.44.192 #Адрес машины
    vm:
      hosts:
        vm-3: #Имя машины
          ansible_host: 158.160.166.41 #Адрес машины
    proxy:
      hosts:
        vm-1: #Имя машины
          ansible_host: 158.160.160.93 #Адрес машины
      
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "s22220733"
    ansible_ssh_private_key_file: "/git/practicum_10/key/id_ed25519"  # Путь к приватному ключу
    connection_protocol: ssh #тип подключения
    ansible_become: true #Становиться ли другим пользователем после подключения # нужно для повышение прав если пользователь не root
    listen_port: 3000
