--- 
- name: изменение имени машины и установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Настройка отдающего Nginx
  hosts: nginx # Будет работать на узлах в группе nginx
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom

- name: Настройка проксирующего Nginx
  hosts: proxy # Будет работать на узлах в группе proxy
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy